[package]
name = "vulkano"
version = "0.1.0"
authors = ["Brian <bk.wood@voafone.co.nz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "*"
vulkano-shaders = "*"
vulkano-win = "*"
winit = "*"